I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 81, in script
    return
Exception: Could not find return label (u'D:\\Black ICE\\\u0438\u0433\u0440\u0430\\the_tenant/game/script.rpy', 1452944000, 58).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 81, in script
    return
  File "D:\Black ICE\игра\renpy\ast.py", line 1331, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "D:\Black ICE\игра\renpy\execution.py", line 391, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'D:\\Black ICE\\\u0438\u0433\u0440\u0430\\the_tenant/game/script.rpy', 1452944000, 58).

Windows-post2008Server-6.2.9200
Ren'Py 6.18.3.761
